### PR TITLE
Feature 144

### PR DESCRIPTION
**Pull request by tonihele**

### CODE REVIEW

**Comment by ufdada** [comment]
Great work, i never knew that the job icons for digging, claiming and reinforcing were actually used ingame :)

**Comment by tonihele** [comment]
I hope they were :D I tried to reverse engineer from YouTube video, I'm on my Linux laptop right now. Trying to avoid Wine etc.

**Comment by ufdada** [comment]
Even if not i would leave them in anyway.

**Comment by tonihele** [comment]
+1

They really help now to see what the little things are up to at least.

**Pull request merged**
