### PR TITLE
Small Controls Update

### PR DESCRIPTION
**Pull request by ArchDemons**
added FunnyCameraContol (follows the target)
added HighLightControl (marks object. In next update will work properly)
added PossessionCameraControl entrance and exit from possession
fixed Possession selection creature

P.S. FunnyCameraContol is temporary solution (for fun) ^_^

### CODE REVIEW

**Comment by tonihele** [comment]
I'm going to do a bit changes. In IInteractiveControl I had the onHover. I thought that I would make a time based effect. But it maybe easier to -> onHoverStart & onHoverEnd. I watched the original a bit and it is pretty precise. So not timed... So I'm going to make your control the base class for Creature & Object control.

**Comment by tonihele** [comment]
I already made our cursor update every 250ms.

**Comment by ArchDemons** [comment]
IInteractiveControl object updates every update cycle in my version of PlayerInteractionState. And no needed remake them on time based. https://github.com/ArchDemons/Keeper/commit/a1e13e52b391b96612daa7ebd0356353c48235b0#diff-03046a7f8c30284e124b82b86e5bf024R220

**Comment by tonihele** [comment]
Mmm, that was the one merged? For me it doesn't work. It just flickers them in red. And feels a bit more hack. Better to let the controls implement the stuff since there are some factors that affect the decision that should it turn red. Better to be figured out in the object/creature control

**Comment by ArchDemons** [comment]
that does not work, because it is not merged. I will prepare a PR in the near future

**Comment by tonihele** [comment]
Here:
https://github.com/tonihele/OpenKeeper/commit/4a38aea710d11581aed38e157d60c5966dd56d67

The hierarchy is a bit funny now perhaps, but it works.

**Comment by tonihele** [comment]
Ah ok, I misunderstood:

> In next update will work properly

**Comment by tonihele** [comment]
Cool that transition effect on possession, btw

**Comment by tonihele** [comment]
And for the FunnyCamera, there are several cameras in the original game. Not necessarily this 3rd person kind chase cam, but we could still keep and offer it. Perhaps with more descriptive name ;) But it looks nice so why not

**Comment by ArchDemons** [comment]
LockedCamera is most suitable. Need rename others cameras: TopDownCamera and FirstPersonCamera

**Pull request merged**
