### PR TITLE
Feature 160

### PR DESCRIPTION
**Pull request by ArchDemons**
some base network stuff

### CODE REVIEW

**Comment by ArchDemons** [comment]
Sorry it took so long. I change job and do not know how much time can be given to the project in the future. I'll make small changes at least

**Comment by tonihele** [comment]
Thanks, I'll try this in a minute. Good luck with your new job!

**Comment by ArchDemons** [comment]
I joined to the java programmers in my new work :)

**Comment by tonihele** [comment]
Oh nice :) You have a good reference here :)

**Comment by tonihele** [comment]
Nice work! Creating a server seems to work only one time though. We'll get to that later. At least now we have some base.

**Comment by ArchDemons** [comment]
I could not solve this problem. There's really them even more ... I did not understand, whether it is my curve hands, or errors in game engine

**Pull request merged**
