### PR TITLE
Implement MPD and Secret level selection to main menu

### PR DESCRIPTION
**Pull request by ufdada**
- MPD Level names are translated now
- Level, Secret level and MPD are using the same campaign screen
- Small GUI Improvements

### CODE REVIEW

**Comment by ufdada** [comment]
I am ready to merge now

**Comment by tonihele** [comment]
Great work dude!

**Comment by ufdada** [comment]
Thanks man :). I guess the last change was for the failing mpd levels? Wonder if they implement this special room with id 35 directly to the maploader...

**Comment by tonihele** [comment]
Some normal levels fail as well, at this point it is not really surprising :) But the now added logging and not completely failing helps in finding the bugs & not implemented parts.

**Pull request merged**
