### PR TITLE
refactored setting op LoopMode CYCLE and LOOP

### PR DESCRIPTION
**Pull request by belgianguy**
Now both ModelViewer and CreatureLoader use the same method to determine if the LoopMode is CYCLE or LOOP

### CODE REVIEW

**Comment by tonihele** [comment]
This is good, but a conflict must be solved. There is one part of @ufdada settings/dk folder changes re-applied here, it might be that?

**Comment by belgianguy** [comment]
The conflict was indeed with the DKII folder code, it has been resolved.

**Comment by ufdada** [comment]
you actually removed your bugfix for the Animation NPE

**Comment by belgianguy** [comment]
I looked at the merge window and thought that the args[0] check caused it. And I thought that I should nit merge the spatial children check, as it was already in another PR.

**Comment by ufdada** [comment]
if you rebase (or merge from master) you actually have to take all changes into consideration.

The best way to check if you didn't do anything wrong is the "File changes" tab, it shows the differences to the branch you want to merge.

**Pull request merged**
