### PR TITLE
New Steering test two

### PR DESCRIPTION
**Pull request by ArchDemons**
added ReachOrientation steering (now work better than was)

### CODE REVIEW

**Comment by ArchDemons** [comment]
previous Pull Request we can close, it`s not actual.

**Comment by ufdada** [comment]
Seems like the facing of the hero party or the goblins doesn't work with these changes. At least in level 1.

**Comment by tonihele** [comment]
You mean while in battle? That is not implemented before nor in this PR. But it'll be easy to add such if this works as intended. My collision avoidance caused Antonius' (level 1) patrol route errors, but patrol routes do not have target facing anyway. Just a cautionary tale on how difficult the steering is to tweak...

**Comment by ufdada** [comment]
No i mean when antonius is on patrol and the goblin are simply walking. They are always facing in the same direction

**Comment by tonihele** [comment]
:( God dammit steering lib. Y u no work....

**Comment by ArchDemons** [comment]
> Seems like the facing of the hero party or the goblins doesn't work with these changes. At least in level 1.

I test on custom level with imps. But my changes should not  change direction if creature moving. Only if it stay and have angular velocity. Need some debug

**Comment by ArchDemons** [comment]
Problem was too large zeroLinearSpeedThreshold (more than max linear speed)

**Comment by tonihele** [comment]
I think it works in general. Only thing I wound was that when the creatures start moving, they don't know which way to orientate at first. They do this quick "dance move". Clearly visible on Antonius patrolling. But I'd rather have that than no orientation. It is so minor, given that the rest of the movement stuff aren't perfect either.

**Comment by tonihele** [comment]
Nice work

**Pull request merged**
