### PR TITLE
upload build artifacts

### PR DESCRIPTION
**Pull request by Trass3r**
Allows to download the builds from the Actions tab.
https://github.com/Trass3r/OpenKeeper/actions/runs/1745813856

### CODE REVIEW

**Comment by tonihele** [comment]
Cool, is it the latest build or how many builds?

**Comment by Trass3r** [comment]
Every commit, but I think they clean it up after a while.

**Comment by tonihele** [comment]
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#artifact-and-log-retention-policy

90 days. So it might be that there is nothing if no activity in 90 days

**Comment by Trass3r** [comment]
Yeah for longer lasting builds there are releases.
Which can also be created via Github Actions.

**Comment by tonihele** [comment]
Yep, we are little bit late with our 0.1 milestone. Still some issues.

But yeah, I'm sure this is all good.

**Comment by Trass3r** [comment]
Already worked:
https://github.com/tonihele/OpenKeeper/actions/runs/1747024306

**Pull request merged**
