### PR TITLE
Effects in modelviewer

### PR DESCRIPTION
**Pull request by belgianguy**
Added effects to ModelViewer, some are immedeatly visible, but they don't loop, but others don't appear yet (we handle only Image type atm). The location is hardcoded for now, just zoom out until the whole map is visible and pick one, "Mercenary Enter Effect" is a nice big one that is easily spotted.As is "inferno test launch"

### CODE REVIEW

**Comment by tonihele** [comment]
Add the EffectManager as a state in model viewer. That will make the
effects loop. As it will call the update method. Some manual cleaning for
the effects would be then required however...

**Comment by ufdada** [comment]
A little bit OT, but i see you got the commit from #211 in here, too. Just a little advice from my side: before making another branch switch back to your master branch, update and rebase it and then create another branch.

in console:
```bash
git checkout master             # switch to master branch
git fetch --all -p              # update all remote branches and prune obsolete branches
git rebase <remote-branch>      # (optional) rebase your master branch with another one, like tonihele/master
git branch new_branch           # create new branch
git checkout new_branch         # switch to new branch
```

**Comment by belgianguy** [comment]
Ah, my bad, I thought I had made a clean branch, I'll try to fix it.

**Comment by ufdada** [comment]
You can also just make a new branch like mentioned above and cherry-pick the change you want to add

`git cherry-pick af8f27af23cc84b4dba2c143159f25fa478b731d`

**Comment by belgianguy** [comment]
PR 213 supersedes this one.

**Pull request closed without merging**
