### PR TITLE
Feature 137

### PR DESCRIPTION
**Pull request by ArchDemons**
There are two different ways to flash tiles (in each commit). What way is better ?
* Control on ActionPoint
* Control on WorldState

### CODE REVIEW

**Comment by ArchDemons** [comment]
do not merge. Vote first. I`ll add something else (maybe)

**Comment by ufdada** [comment]
@ArchDemons Is this PR still relevant?

If the WorldState would be in control of the flashing, wouldn't it show up for all players? I don't think that would be a good idea for multiplayer (if it is used there...)

**Comment by tonihele** [comment]
It could be used there. It is just the map design. Every Keeper needs their own map anyway. Now we are just using the master map. Flashing should be eventually then moved the player map. And tagging etc.

We just haven't planned this much yet.

**Comment by ArchDemons** [comment]
Still Relevant. I'm on vacation and I finished this when I get back.

**Comment by ufdada** [comment]
No problem, i was just wondering because it was already 5 months old.

Enjoy your vacation! :)

**Comment by ArchDemons** [comment]
rebased :)

**Comment by tonihele** [comment]
Look good to me. Didn't test it though.

**Comment by ufdada** [comment]
I'll test it.

**Comment by ufdada** [comment]
Okay checked it, solid blocks are getting highlighted as they should. But there is still no highlighting on path areas or rooms (for example the room building tutorial in level 1).

**Comment by tonihele** [comment]
Thanks, that is probably okay. I think this is more a refactor & stabilization than a feature addition.

**Comment by ArchDemons** [comment]
> Okay checked it, solid blocks are getting highlighted as they should. But there is still no highlighting on path areas or rooms (for example the room building tutorial in level 1).

Fixed. I forgot about highlighting tiles for building rooms

**Comment by ufdada** [comment]
Looks great now! :)

**Pull request merged**
