### PR TITLE
Pickup from card

### PR DESCRIPTION
**Pull request by ArchDemons**
we need creatures population calculator like workers population calculator

### CODE REVIEW

**Comment by ufdada** [comment]
Resolves #223 .

Looks good to me.

There is a slight delay when trying to pickup several minions very fast, but it seems it is because of our state design (it gets executed every tick)

**Comment by ArchDemons** [comment]
nifty interprets fasts clicks as double click. And that is another handler

**Comment by ufdada** [comment]
That makes sence :).
Can we attach the creature pickup to the dblclick handler? It would picking up a few creatures less tricky.

**Comment by tonihele** [comment]
See:
https://github.com/tonihele/OpenKeeper/pull/250

I think the same is on zooming on the cards as well...

**Comment by tonihele** [comment]
I don't think we are utilizing the double click anywhere? Should check the code. If not, just set the delay to 100ms or even lower

**Comment by ArchDemons** [comment]
If we can lower delay between click we should do that

**Comment by tonihele** [comment]
```
nifty.setGlobalProperties(new Properties());
nifty.getGlobalProperties().setProperty("MULTI_CLICK_TIME", "100");

```
?

**Comment by ArchDemons** [comment]
nifty.getGlobalProperties().setProperty("MULTI_CLICK_TIME", "1");

:)

**Comment by tonihele** [comment]
If we aren't using double click anywhere, why not :) Can you test?

**Comment by ArchDemons** [comment]
this solution works. But where I should put it (what class)? Main -> simpleInitApp() ?

**Comment by tonihele** [comment]
https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/Main.java#L357 ? Yeah, might be most logical

**Comment by tonihele** [comment]
Great thanks! Imps zoomTo doesn't work though.

**Comment by ArchDemons** [comment]
fix zoomTo in next commit

**Pull request merged**
