### PR TITLE
Feature 170

### PR DESCRIPTION
**Pull request by ArchDemons**
added camera rotation control around action point
PlayerTriggerControl and PlayerManaControl moved to Keeper
fixed TriggerControl action and activation
removed debug interactions (claiming and digging)

some known bugs: 
crash game in level 1 (access from other thread). I think this is some trigger action

### CODE REVIEW

**Comment by ufdada** [comment]
Why did you remove the debug interactions?
I still think they are quite useful for testing things (like triggers) without having to play the whole map.

Maybe we should hide them better later (like using a special cheat code or console command).

**Comment by ArchDemons** [comment]
removed only claiming and reinforcing tiles. This options already tested and we have imps with AI :)

**Comment by ufdada** [comment]
That's right, but if you want to claim or dig something which isn't directly reachable for your imps you may have to wait several minutes or it isn't even possible (like if there are enemies around and your imps are running away the whole time).

**Comment by tonihele** [comment]
Looks good, but @ufdada has a point about the debug features. Maybe we should keep those at least for awhile longer.

**Comment by tonihele** [comment]
> crash game in level 1 (access from other thread). I think this is some trigger action

Currently creating a party can cause this. Not much else I guess. The spawn creature should always create the creature to the internal registry and queue the graphical presentation for later. The movement too is detached from the visual presentation. A known issue I'll try to sort soonish.

Physics introduction may complicate this further because it is synced with the graphics as far as I know.

**Comment by ArchDemons** [comment]
all done

**Comment by tonihele** [comment]
Great!

**Pull request merged**
